### ISSUE TITLE
Plots

### ISSUE THREAD

**Issue by LucaYoy** [LucaYoy/Many-quantum-bodies-using-quantum-computing#14]
- [x] plot I matrix as a colormap
- [x] plot the average I with distance 
- [x] plot von neuman entropy against bond length
- [x] plot overlap
- [x] plot energy

**Comment by LucaYoy** [comment]
@NicholasSynesi @as2457 does this look okai? Im still waiting to check against Nicholas if I did my mutual info and entropy correctly but I produced this plot 
![entropyPlots](https://user-images.githubusercontent.com/40484649/222924011-68f4462e-3afb-4a6b-8ed6-c3aae736e6a9.png)

**Comment by LucaYoy** [comment]
@NicholasSynesi @as2457 Plots for color map
![matrixCmPlots](https://user-images.githubusercontent.com/40484649/222976539-c4587498-3bd2-45d1-aa3d-02bcf8e5578a.png)

**Comment by LucaYoy** [comment]
plots for J. There are some problems when trying log scale since it's trying to do log(0).
![JPlots](https://user-images.githubusercontent.com/40484649/223214590-ed4f907b-d622-43c8-b836-2d7b5f8fcc71.png)

**Comment by AdamSmith-physics** [comment]
@LucaYoy This all looks pretty good to me. It may be that your optimisation has not quite finished as for an even number of qubits you would also expect the results to be inversion symmetric. This may not be the case but it would be my expectation.

For the final plot, the distance d=0 doesn't make sense. It should start from 1 and then the log scale should work.

Note: Please make sure to add to your notebook as well. I know this is annoying since you are clearly doing it here, but the notebook is what you'll get marked on

**Comment by LucaYoy** [comment]
@as2457 Hmm I still get the same problem my graph on log log scale goes wrong ☠️

![JPlots](https://user-images.githubusercontent.com/40484649/223718625-7ad3f17d-76be-4ef4-b306-a447f224c6aa.png)

**Comment by AdamSmith-physics** [comment]
@LucaYoy Actually, I think this looks fine. 

What you need to do is limit the y-values. It makes sense that this value should go to exactly zero for a certain distance for shallow circuit. you just need to focus on the range of y-values when it is not zero (-infinity on log plot).

Also, when you plot, plot it normally and then use 
plt.yscale("log")
plt.xscale("log")
This way the ticks will still correspond to d and not log(d), which is a lot easier to read.

**Comment by LucaYoy** [comment]
@as2457 What should be on the x axis for the overlap and energy plots? was it layers used for the approximation or was it cycles in the optimisation process?

**Comment by AdamSmith-physics** [comment]
@LucaYoy it was layers in the circuit. 

Plotting against iterations will be useful for figuring out if it has converged though!
