### ISSUE TITLE
Collect DB and plot correlation functions

### ISSUE THREAD

**Issue by LucaYoy** [LucaYoy/Many-quantum-bodies-using-quantum-computing#47]
- [x] Collect DB of states
- [x] plot entropy comparisons
- [x] plot energy comparisons
- [x] plot mutual info comparisons

**Comment by LucaYoy** [comment]
@as2457 So im having some trouble trying to compute the state from the optimised circuit returned from the HPC. Im now saving the circuit object in a pkl file that contains the optimised gates and then in my script using .computeUsingTensorDot() method to get the state. The problem is that I get memory issues and my state Mac seems to not be able to compute the state. Is this again because of the reduce() ? 
![Screenshot 2023-04-07 at 09 52 26](https://user-images.githubusercontent.com/40484649/230559267-51993487-85d9-43a7-a51f-4e0316079d5d.png)

**Comment by LucaYoy** [comment]
Update: Changed reduce method and I get same problem

**Comment by LucaYoy** [comment]
@as2457 I need help with an error message that is driving me crazy since I cant find the bug. Im trying to send Nicholas the optimised gates which I need to extract from my DB of circuit objects. I have the following script that keeps giving this error:
![Screenshot 2023-04-14 at 13 05 34](https://user-images.githubusercontent.com/40484649/232015454-92c045d3-ad53-42cb-b589-c1a1b7bd5d17.png)

It tells me that the directory doesn't exist but it clearly exists since the code ran once in the loop and now it decided not to work anymore in the second iteration. Also I dont really understand the error message.

**Comment by LucaYoy** [comment]
Nevermind I found my error... Im using g variable in two places meaning different things....

**Comment by LucaYoy** [comment]
@NicholasSynesi you can now find the optimised gates DB on main branch, in the folder mainScripts/pklFiles/DBNicholas

**Comment by LucaYoy** [comment]
@NicholasSynesi maybe in your plots it would be a good idea to plot only for layers 3,5,7 to avoid clutter on one graph since its quite hard to understand what's going on with so many lines

**Comment by NicholasSynesi** [comment]
I was gonna wait to plot exactly what we'll need, these plots haven't been properly scaled or anything yet, it's just the data. Once we determine exactly what graphs we want in our paper I'll change them up.

**Comment by NicholasSynesi** [comment]
From what I can see, the G = 1 model doesn't seem to be well approximated at all, not sure if it's an error on my end because I wasn't expecting that. For the others, the approximation seems to be almost perfect for 7 layers, but before that it's quite messy

**Comment by NicholasSynesi** [comment]
![image](https://user-images.githubusercontent.com/117459444/233102763-c1340ddd-9bf7-4927-b9aa-ff708facfec8.png)

@LucaYoy any idea why the G = 1 approximation is nowhere even close?

**Comment by LucaYoy** [comment]
@NicholasSynesi from the above it seems that the plot for the target state is not correct rather than the approximation plots

**Comment by NicholasSynesi** [comment]
I do agree but I've been consistent in how I plot, and the exact state for J h G = 1 'should' be
![image](https://user-images.githubusercontent.com/117459444/233160346-bdfe320b-4b7d-435a-aa48-4127eb9a4a0f.png)

But the fact the approximation above appears to be approximating something different I wonder what the error could be. I'll have a look now

**Comment by LucaYoy** [comment]
I have no idea then ☠️ Is this with both your database and mine ?

**Comment by NicholasSynesi** [comment]
No, I'll set some of mine to run now then

**Comment by LucaYoy** [comment]
make sure 150 000 sweeps, I don't think its gonna be done till tmr our meeting tho
