### ISSUE TITLE
Graphing all data

### ISSUE THREAD

**Issue by NicholasSynesi** [LucaYoy/Many-quantum-bodies-using-quantum-computing#48]
Using Luca's database of gates, I'll plot the entanglement entropy, colour matrices, mutual information, and energy as the state properties. Once we have the collection of graphs, we'll choose what we want to put in the report.

**Comment by LucaYoy** [comment]
@NicholasSynesi what about g=1 model?

**Comment by NicholasSynesi** [comment]
they should be there now
